# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:latest
      - image: circleci/mariadb:latest
        command: mysqld
          environment:
            MYSQL_USER: blue
            MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout

      - run:
          name: Prepare environment
          command: |
            sudo apt update
            sudo apt install -y mariadb-server
            curl -o wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp
            sudo mv wp /usr/local/bin
            echo $(openssl rand -hex 8) > /tmp/wp-password
            wp core download --path=wordpress
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install gd
            zip -r blue-storage.zip blue-storage/
      - run:
          name: Setup WordPress
          command: |
            mysql -u blue -e "create database wordpress"
            wp core download --path=wordpress
            wp config create --dbname=wordpress --dbuser=blue --path=wordpress/
            wp config set WP_DEBUG true --path=wordpress/
            wp config set WP_DEBUG_LOG /tmp/wp-debug.log --path=wordpress/
            wp core install --url=plugin.test --title="Blue Storage" --admin_user=blue --admin_email=blue@plugin.test --prompt=admin_password < /tmp/wp-password
            wp plugin install blue-storage.zip --path=wordpress/ --activate

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      #- run: ./vendor/bin/codecept build
      #- run: ./vendor/bin/codecept run
